
# GET https://node-ap-is.vercel.app/api/form/all_forms


//Get All Forms
# GET http://localhost:8000/api/form/all_forms HTTP/1.1

//get Form by Id
# GET http://localhost:8000/api/form/64c084c17301ef1be4ca464c HTTP/1.1

//delete a form by ID
# GET http://localhost:8000/api/form/delete/64c084c17301ef1be4ca464c HTTP/1.1


//delete all the forms
GET http://localhost:8000/api/form/admin_delete_all_forms?ticket=Techno HTTP/1.1

//create a form
# POST https://node-ap-is.vercel.app/api/form/create_form
# POST http://localhost:8000/api/form/create_form HTTP/1.1
# content-type: application/json

# {
#     "first_name": "sample1",
#     "last_name": "sample last1",
#     "mobile_number":9999999999,
#     "state":"Rajasthan",
#     "country":"India",
#     "email":"mo.saleem.ts@gmail.com",
#     "pincode":302020

# }

//update a form
# POST http://localhost:8000/api/form/update HTTP/1.1
# content-type: application/json

# {
#     "id":"64c082d1995ec041a8afd106",
#     "first_name": "samplex",
#     "last_name": "sample lastx",
#     "mobile_number":999999999,
#     "state":"Rajasthan",
#     "country":"India",
#     "email":"mo.saleem.ts@gmail.com",
#     "pincode":302020

# }


